const mongoose = require('mongoose');
const Scrip = require('./models/Scrip');
const Watchlist = require('./models/Watchlist');
const Order = require('./models/Order');
require('dotenv').config();

const MONGO_URI = process.env.MONGO_URI;

// NIFTY 500 - Expanded List
const nifty500 = [
    "NSE:RELIANCE-EQ", "NSE:TCS-EQ", "NSE:HDFCBANK-EQ", "NSE:ICICIBANK-EQ", "NSE:INFY-EQ", "NSE:HUL-EQ", "NSE:BHARTIARTL-EQ", "NSE:SBIN-EQ", "NSE:ITC-EQ", "NSE:LICI-EQ", "NSE:LTIM-EQ", "NSE:ADANIENT-EQ", "NSE:BAJFINANCE-EQ", "NSE:KOTAKBANK-EQ", "NSE:HCLTECH-EQ", "NSE:AXISBANK-EQ", "NSE:ASIANPAINT-EQ", "NSE:MARUTI-EQ", "NSE:SUNPHARMA-EQ", "NSE:TITAN-EQ", "NSE:ULTRACEMCO-EQ", "NSE:TATAMOTORS-EQ", "NSE:BAJAJFINSV-EQ", "NSE:ONGC-EQ", "NSE:NTPC-EQ", "NSE:WIPRO-EQ", "NSE:JSWSTEEL-EQ", "NSE:POWERGRID-EQ", "NSE:HINDALCO-EQ", "NSE:L&T-EQ", "NSE:ADANIPORTS-EQ", "NSE:GRASIM-EQ", "NSE:TATASTEEL-EQ", "NSE:NESTLEIND-EQ", "NSE:M&M-EQ", "NSE:ADANIPOWER-EQ", "NSE:ADANIGREEN-EQ", "NSE:UPL-EQ", "NSE:ZOMATO-EQ", "NSE:PAYTM-EQ", "NSE:NYKAA-EQ", "NSE:TECHM-EQ", "NSE:CIPLA-EQ", "NSE:DRREDDY-EQ", "NSE:SBILIFE-EQ", "NSE:HDFCLIFE-EQ", "NSE:BAJAJ-AUTO-EQ", "NSE:EICHERMOT-EQ", "NSE:BPCL-EQ", "NSE:INDUSINDBK-EQ", "NSE:DIVISLAB-EQ", "NSE:APOLLOHOSP-EQ", "NSE:TATACONSUM-EQ", "NSE:BRITANNIA-EQ", "NSE:SHREECEM-EQ", "NSE:TATACOMM-EQ", "NSE:BEL-EQ", "NSE:HAL-EQ", "NSE:IRCTC-EQ", "NSE:COALINDIA-EQ", "NSE:GAIL-EQ", "NSE:IOC-EQ", "NSE:DLF-EQ", "NSE:PIDILITIND-EQ", "NSE:SIEMENS-EQ", "NSE:HAVELLS-EQ", "NSE:COLPAL-EQ", "NSE:DABUR-EQ", "NSE:GODREJCP-EQ", "NSE:MARICO-EQ", "NSE:AMBUJACEM-EQ", "NSE:ACC-EQ", "NSE:HEROMOTOCO-EQ", "NSE:TVSMOTOR-EQ", "NSE:ASHOKLEY-EQ", "NSE:CHOLAFIN-EQ", "NSE:MUTHOOTFIN-EQ", "NSE:SRF-EQ", "NSE:PIIND-EQ", "NSE:TRENT-EQ", "NSE:AUBANK-EQ", "NSE:IDFCFIRSTB-EQ", "NSE:YESBANK-EQ", "NSE:FEDERALBNK-EQ", "NSE:BANDHANBNK-EQ", "NSE:MPHASIS-EQ", "NSE:PERSISTENT-EQ", "NSE:COFORGE-EQ", "NSE:DIXON-EQ", "NSE:POLYCAB-EQ",
    "NSE:VI-EQ", "NSE:SUZLON-EQ", "NSE:IDEA-EQ", "NSE:IRFC-EQ", "NSE:RVNL-EQ", "NSE:NHPC-EQ", "NSE:IRCON-EQ", "NSE:PFC-EQ", "NSE:RECLTD-EQ", "NSE:PNB-EQ", "NSE:BOB-EQ", "NSE:CANBK-EQ", "NSE:UNIONBANK-EQ", "NSE:INDIANB-EQ", "NSE:MAHABANK-EQ", "NSE:CENTRALBK-EQ", "NSE:IOB-EQ", "NSE:UCOBANK-EQ", "NSE:BOM-EQ", "NSE:ABB-EQ", "NSE:ADANIENSOL-EQ", "NSE:ATGL-EQ", "NSE:AWL-EQ", "NSE:ABCAPITAL-EQ", "NSE:ABFRL-EQ", "NSE:APLLTD-EQ", "NSE:AJANTPHARM-EQ", "NSE:ALKEM-EQ", "NSE:ALOKINDS-EQ", "NSE:ARE&M-EQ", "NSE:APOLLOTYRE-EQ", "NSE:ASTERDM-EQ", "NSE:ASTRAL-EQ", "NSE:ATUL-EQ", "NSE:AUROPHARMA-EQ", "NSE:AVANTIFEED-EQ", "NSE:BAJAJHLDNG-EQ", "NSE:BALAMINES-EQ", "NSE:BALKRISIND-EQ", "NSE:BALRAMCHIN-EQ", "NSE:BANKBARODA-EQ", "NSE:BANKINDIA-EQ", "NSE:BATAINDIA-EQ", "NSE:BAYERCROP-EQ", "NSE:BERGEPAINT-EQ", "NSE:BDL-EQ", "NSE:BHARATFORG-EQ", "NSE:BHEL-EQ", "NSE:BIOCON-EQ", "NSE:BIRLACORPN-EQ", "NSE:BSOFT-EQ", "NSE:BLUESTARCO-EQ", "NSE:BOSCHLTD-EQ", "NSE:CESC-EQ", "NSE:CGPOWER-EQ", "NSE:CAMPUS-EQ", "NSE:CARBORUNIV-EQ", "NSE:CASTROLIND-EQ", "NSE:CEAT-EQ", "NSE:CHAMBLFERT-EQ", "NSE:CHENNPETRO-EQ", "NSE:CHOLAHLDNG-EQ", "NSE:CUB-EQ", "NSE:CLEAN-EQ", "NSE:COCHINSHIP-EQ", "NSE:CONCOR-EQ", "NSE:COROMANDEL-EQ", "NSE:CROMPTON-EQ", "NSE:CUMMINSIND-EQ", "NSE:CYIENT-EQ", "NSE:DCMSHRIRAM-EQ", "NSE:DEEPAKFERT-EQ", "NSE:DEEPAKNTR-EQ", "NSE:DELHIVERY-EQ", "NSE:DEVYANI-EQ", "NSE:FDSL-EQ", "NSE:FORTIS-EQ", "NSE:GLANDS-EQ", "NSE:GLENMARK-EQ", "NSE:GMMPFAUDLR-EQ", "NSE:GMRINFRA-EQ", "NSE:GNFC-EQ", "NSE:GPPL-EQ", "NSE:GRSE-EQ", "NSE:GSFC-EQ", "NSE:GSPL-EQ", "NSE:GUJGASLTD-EQ", "NSE:GMDCLTD-EQ", "NSE:GODREJIND-EQ", "NSE:GODREJPROP-EQ", "NSE:GRANULES-EQ", "NSE:GRAPHITE-EQ", "NSE:GOCLCORP-EQ", "NSE:GUJALKALI-EQ", "NSE:HFCL-EQ", "NSE:HAPPSTMNDS-EQ", "NSE:HINDCOPPER-EQ", "NSE:HINDPETRO-EQ", "NSE:HINDZINC-EQ", "NSE:HUDCO-EQ", "NSE:IDBI-EQ", "NSE:IDFC-EQ", "NSE:IFCI-EQ", "NSE:IGL-EQ", "NSE:INDHOTEL-EQ", "NSE:INDIACEM-EQ", "NSE:INDIAMART-EQ", "NSE:IEX-EQ", "NSE:INDIGO-EQ", "NSE:IRB-EQ", "NSE:ITI-EQ", "NSE:JBCHEPHARM-EQ", "NSE:JKCEMENT-EQ", "NSE:JKLAKSHMI-EQ", "NSE:JKPAPER-EQ", "NSE:JMFINANCIL-EQ", "NSE:JUBLFOOD-EQ", "NSE:JUBLINGREA-EQ", "NSE:JUBLPHARMA-EQ", "NSE:KEC-EQ", "NSE:KPITTECH-EQ", "NSE:KNRCON-EQ", "NSE:KALYANKJIL-EQ", "NSE:KANSAINER-EQ", "NSE:KARURVYSYA-EQ", "NSE:KRSNAA-EQ", "NSE:LTTS-EQ", "NSE:LICHSGFIN-EQ", "NSE:LAURUSLABS-EQ", "NSE:LXCHEM-EQ", "NSE:MRF-EQ", "NSE:MTARTECH-EQ", "NSE:MGL-EQ", "NSE:MAHINDCIE-EQ", "NSE:M&MFIN-EQ", "NSE:MAHLIFE-EQ", "NSE:MANAPPURAM-EQ", "NSE:MRPL-EQ", "NSE:METROPOLIS-EQ", "NSE:MFSL-EQ", "NSE:MINDACORP-EQ", "NSE:MOTILALOFS-EQ", "NSE:NATCOPHARM-EQ", "NSE:NBCC-EQ", "NSE:NCC-EQ", "NSE:NESCO-EQ", "NSE:NH-EQ", "NSE:NLCINDIA-EQ", "NSE:NMDC-EQ", "NSE:NOCIL-EQ", "NSE:OBEROIRLTY-EQ", "NSE:OFSS-EQ", "NSE:OIL-EQ", "NSE:PAGEIND-EQ", "NSE:PPLPHARMA-EQ", "NSE:PATANJALI-EQ", "NSE:PETRONET-EQ", "NSE:PHOENIXLTD-EQ", "NSE:PNCINFRA-EQ", "NSE:POONAWALLA-EQ", "NSE:PRAJIND-EQ", "NSE:PRESTIGE-EQ", "NSE:PRINCEPIPE-EQ", "NSE:PRSMJOHNSN-EQ", "NSE:QUESS-EQ", "NSE:RBLBANK-EQ", "NSE:RITES-EQ", "NSE:RADICO-EQ", "NSE:RAIN-EQ", "NSE:RAJESHEXPO-EQ", "NSE:RAMCOCEM-EQ", "NSE:RATNAMANI-EQ", "NSE:RAYMOND-EQ", "NSE:REDINGTON-EQ", "NSE:RELAXO-EQ", "NSE:RHIM-EQ", "NSE:SANOFI-EQ", "NSE:SAPPHIRE-EQ", "NSE:SHOPERSTOP-EQ", "NSE:SONACOMS-EQ", "NSE:STARHEALTH-EQ", "NSE:SUDARSCHEM-EQ", "NSE:SUNTECK-EQ", "NSE:SYNGENE-EQ", "NSE:TCI-EQ", "NSE:TCIEXP-EQ", "NSE:TTML-EQ", "NSE:TANLA-EQ", "NSE:TATAELXSI-EQ", "NSE:TATAIEX-EQ", "NSE:TATAMTRDVR-EQ", "NSE:TATAPOWER-EQ", "NSE:TATAINVEST-EQ", "NSE:TEAMLEASE-EQ", "NSE:THERMAX-EQ", "NSE:TIMKEN-EQ", "NSE:TIPSMUSIC-EQ", "NSE:TRITURBINE-EQ", "NSE:TRIDENT-EQ", "NSE:UJJIVANSFB-EQ", "NSE:UNITDSPR-EQ", "NSE:VGUARD-EQ", "NSE:VTL-EQ", "NSE:VARROC-EQ", "NSE:VBL-EQ", "NSE:VEDL-EQ", "NSE:VOLTAS-EQ", "NSE:WELCORP-EQ", "NSE:WELSPUNLIV-EQ", "NSE:WHIRLPOOL-EQ", "NSE:WOCKPHARMA-EQ", "NSE:ZENSARTECH-EQ", "NSE:ZYDUSLIFE-EQ",
    // Adding more to reach closer to 500
    "NSE:JKTYRE-EQ", "NSE:RPOWER-EQ", "NSE:RTNPOWER-EQ", "NSE:SOUTHBANK-EQ", "NSE:IDFC-EQ", "NSE:GAYAPROJ-EQ", "NSE:HDIL-EQ", "NSE:JPASSOCIAT-EQ", "NSE:JINDALSTEL-EQ", "NSE:MAHABANK-EQ", "NSE:J&KBANK-EQ", "NSE:KTKBANK-EQ", "NSE:DCBBANK-EQ", "NSE:KARURVYSYA-EQ", "NSE:CSBBANK-EQ", "NSE:DHANBANK-EQ", "NSE:CITYUNION-EQ", "NSE:FSL-EQ", "NSE:GENESYS-EQ", "NSE:HCL-INSYS-EQ", "NSE:SUBEXLTD-EQ", "NSE:ROLTA-EQ", "NSE:MINDTREE-EQ", "NSE:HEXAWARE-EQ", "NSE:NIITLTD-EQ", "NSE:LTI-EQ", "NSE:SONATSOFTW-EQ", "NSE:CYIENT-EQ", "NSE:TATAELXSI-EQ", "NSE:ZENSARTECH-EQ", "NSE:PERSISTENT-EQ", "NSE:KPIT-EQ", "NSE:AFFLE-EQ", "NSE:ROUTE-EQ", "NSE:TANLA-EQ", "NSE:NAZARA-EQ", "NSE:MASTEK-EQ", "NSE:COFORGE-EQ", "NSE:BCG-EQ", "NSE:63MOONS-EQ", "NSE:HDFCAMC-EQ", "NSE:NAM-INDIA-EQ", "NSE:UTIAMC-EQ", "NSE:CAMS-EQ", "NSE:CDSL-EQ", "NSE:MCX-EQ", "NSE:BSE-EQ", "NSE:ANGELONE-EQ", "NSE:MOTILALOFS-EQ", "NSE:ISEC-EQ", "NSE:GEPL-EQ", "NSE:EDELWEISS-EQ", "NSE:RELIGARE-EQ", "NSE:L&TFH-EQ", "NSE:M&MFIN-EQ", "NSE:CHOLAFIN-EQ", "NSE:SHRIRAMFIN-EQ", "NSE:MUTHOOTFIN-EQ", "NSE:MANAPPURAM-EQ", "NSE:BAJAJFINSV-EQ", "NSE:BAJFINANCE-EQ", "NSE:POONAWALLA-EQ", "NSE:AAVAS-EQ", "NSE:HOMEFIRST-EQ", "NSE:CANFINHOME-EQ", "NSE:PNBHOUSING-EQ", "NSE:REPCOHOME-EQ", "NSE:HUDCO-EQ", "NSE:GICRE-EQ", "NSE:NIACL-EQ", "NSE:HDFCLIFE-EQ", "NSE:SBILIFE-EQ", "NSE:ICICIPRULI-EQ", "NSE:ICICIGI-EQ", "NSE:STARHEALTH-EQ", "NSE:TATACOMM-EQ", "NSE:BHARTIARTL-EQ", "NSE:IDEA-EQ", "NSE:MTNL-EQ", "NSE:HFCL-EQ", "NSE:ITI-EQ", "NSE:TEJASNET-EQ", "NSE:STERTOOLS-EQ", "NSE:BHEL-EQ", "NSE:BEL-EQ", "NSE:HAL-EQ", "NSE:BDL-EQ", "NSE:COCHINSHIP-EQ", "NSE:MAZDOCK-EQ", "NSE:GRSE-EQ", "NSE:HINDCOPPER-EQ", "NSE:NATIONALUM-EQ", "NSE:VEDL-EQ", "NSE:HINDZINC-EQ", "NSE:NMDC-EQ", "NSE:SAIL-EQ", "NSE:TATASTEEL-EQ", "NSE:JSWSTEEL-EQ", "NSE:JINDALSTEL-EQ", "NSE:HINDALCO-EQ", "NSE:ADANIENT-EQ"
];

// Deduplicate list
const uniqueNifty500 = [...new Set(nifty500)];

const seedScrips = async () => {
    try {
        await mongoose.connect(MONGO_URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        });
        console.log(`Connected to MongoDB for scaling to ${uniqueNifty500.length} stocks...`);

        // IMPORTANT: Clear broken references
        await Watchlist.deleteMany({});
        await Order.deleteMany({});
        console.log("Cleared existing watchlists and orders to prevent null reference errors.");

        // Clear existing scrips
        await Scrip.deleteMany({});
        console.log("Cleared existing scrips.");

        const scripsToInsert = uniqueNifty500.map((s, index) => {
            const [exchangePart, rest] = s.split(':');
            const [symbol, scriptType] = rest.split('-');
            
            return {
                scriptName: symbol,
                symbol: symbol,
                exchange: exchangePart,
                scriptType: scriptType || 'EQ',
                segment: 'CM',
                scriptToken: 4000 + index, 
                scriptKey: `${exchangePart}_${symbol}`,
                originalName: s,
                lastPrice: Math.floor(Math.random() * 10000) + 50, 
                percentageChange: (Math.random() * 8 - 4).toFixed(2), 
                changeInPrice: 0,
                low: 0,
                high: 0,
                open: 0,
                close: 0
            };
        });

        await Scrip.insertMany(scripsToInsert);
        console.log(`Successfully seeded ${scripsToInsert.length} major Indian stocks!`);
        
        mongoose.connection.close();
    } catch (err) {
        console.error("Seeding failed:", err);
        process.exit(1);
    }
};

seedScrips();
